-- PG TASK 3: POSTGRESQL RELATIONAL STRUCTURES
-- Tamar Tutisani
-- Module: PG_DWH
-----------------------------------------------------------------------------
-- EXECUTION ORDER:
--  PREREQUISITE: Connect to test_db, create/set search_path to labs
--  Task 1: Unlogged table performance
--  Task 2: Inherited tables
--  Task 3: BRIN vs B-Tree indexes
--  Task 4: GIN vs GiST indexes
--  Task 5: CSV file as a foreign table + materialized view
-----------------------------------------------------------------------------


-- PREREQUISITE: Connect to test_db and set search_path
-----------------------------------------------------------------------------

-- Create the schema if it does not exist yet in this database
CREATE SCHEMA IF NOT EXISTS labs;

SET search_path TO labs, public;
SHOW search_path;

-- Drop and recreate person table (fresh start for this task)
DROP TABLE IF EXISTS labs.person CASCADE;

CREATE TABLE labs.person (
    id INTEGER NOT NULL,
    name VARCHAR(15)
);

INSERT INTO labs.person (id, name)
SELECT v.id, v.name
FROM (VALUES
    (1, 'Bob'),
    (2, 'Alice'),
    (3, 'Robert')
) AS v(id, name)
WHERE NOT EXISTS (
    SELECT 1
    FROM labs.person p
    WHERE p.id = v.id
);

SELECT * 
FROM labs.person;


-----------------------------------------------------------------------------
-- TASK 1: PERFORMANCE WITH UNLOGGED TABLES
-----------------------------------------------------------------------------
-- Unlogged tables skip the Write-Ahead Log (WAL). Because WAL writes are
-- the bottleneck for INSERT-heavy workloads, unlogged tables are typically
-- 3-10x faster to write to. Trade-off: data is truncated on crash/restart.

-- 1. Create a regular (logged) table
DROP TABLE IF EXISTS labs.test_simple;

CREATE TABLE labs.test_simple (
    a INT,
    b INT
);

-- 2a. Inserting 1,000,000 rows into logged table and noting the time
INSERT INTO labs.test_simple
SELECT generate_series(1, 1000000);
-- this is shown in screenshot task1_1.png

-- 2b. Insert 5,000,000 more rows
INSERT INTO labs.test_simple
SELECT generate_series(1, 5000000);
-- this is shown in screenshot task1_2.png

-- 3. Create an UNLOGGED table with the same structure
DROP TABLE IF EXISTS labs.test_unlogged;

CREATE UNLOGGED TABLE labs.test_unlogged (
    a INT,
    b INT
);

-- 4a. Insert 1,000,000 rows into unlogged table
INSERT INTO labs.test_unlogged
SELECT generate_series(1, 1000000);
-- this is shown in screenshot task1_3.png

-- 4b. Insert 5,000,000 more rows
INSERT INTO labs.test_unlogged
SELECT generate_series(1, 5000000);
-- this is shown in screenshot task1_4.png

-- Compare row counts to confirm both tables have the same data
SELECT 'test_simple' AS table_name, 
	   COUNT(*) 
FROM labs.test_simple
UNION ALL
SELECT 'test_unlogged' AS table_name,
	   COUNT(*) 
FROM labs.test_unlogged;
-- this is shown in screenshot task1_5.png

/*
EXPECTED OBSERVATIONS:
- Unlogged inserts are noticeably faster (often 3-10x) because PostgreSQL
  skips writing to WAL. WAL is the main write bottleneck for small random
  INSERTs.
- For the 5M insert, the gap is even more pronounced.
- Use cases for unlogged: staging/temp ETL data, session data, anything
  that can be rebuilt if the server crashes (e.g. our SA layer SRC_ tables
  during ETL runs — we can always re-load from the EXT_ foreign tables).
- Downside: on crash PostgreSQL TRUNCATES the unlogged table automatically
  on restart. Also, unlogged tables are not replicated.
*/


-----------------------------------------------------------------------------
-- TASK 2: UNDERSTANDING INHERITED TABLES
-----------------------------------------------------------------------------
-- Inheritance lets a child table share all columns of a parent while
-- adding its own. Queries on the parent automatically include child rows
-- unless ONLY is specified.

-- 1. Create a child table that inherits from person
DROP TABLE IF EXISTS labs.users CASCADE;

CREATE TABLE labs.users (
    user_id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    login   VARCHAR(30)
) INHERITS (labs.person);

-- 2. Insert rows into users (child)
INSERT INTO labs.users (id, name, login)
SELECT v.id, v.name, v.login
FROM (VALUES
    (1, 'new Bob', 'NewLogin'),
    (999, 'TestUser', 'TestLogin')
) AS v(id, name, login)
WHERE NOT EXISTS (
    SELECT 1
    FROM labs.users u
    WHERE u.id = v.id
);

-- 3. Selects: observe the difference between person, ONLY person, users
SELECT * 
FROM labs.users;
-- Returns only users rows (2 rows)
-- this is shown in screenshot task2_1.png

SELECT * 
FROM labs.person;
-- Returns person rows (3 original) PLUS users rows (2) = 5 rows total
-- Child rows are visible in the parent query by default
-- this is shown in screenshot task2_2.png

SELECT * 
FROM ONLY labs.person;
-- Returns only the 3 original person rows, ONLY excludes child tables
-- this is shown in screenshot task2_3.png

-- 4. UPDATE on parent affects BOTH parent-only and child rows
UPDATE labs.person
SET name = 'not Bob'
WHERE id = 1;
-- This updates id=1 in BOTH person (Bob row) AND users (new Bob row)
-- because users inherits from person

SELECT * 
FROM labs.person; -- shows 'not Bob' in two places
-- this is shown in screenshot task2_4.png

SELECT * 
FROM labs.users; -- also shows 'not Bob'
-- this is shown in screenshot task2_5.png

-- Rewrite: change name ONLY in person table (not users)
UPDATE ONLY labs.person
SET name = 'Bob_restored'
WHERE id = 1;

SELECT * 
FROM labs.person; -- person row restored; users row still 'not Bob'
-- this is shown in screenshot task2_6.png

SELECT * 
FROM labs.users; -- users row unchanged
-- this is shown in screenshot task2_7.png

-- 5. ALTER parent: columns propagate to child; CHECK with NO INHERIT does NOT
ALTER TABLE labs.person 
ADD COLUMN IF NOT EXISTS status INTEGER DEFAULT 0;
-- status column now appears in BOTH labs.person and labs.users

DO $$
BEGIN
    IF NOT EXISTS (
        SELECT 1 FROM pg_constraint WHERE conname = 'chk_person_status'
    ) THEN
        ALTER TABLE labs.person
            ADD CONSTRAINT chk_person_status CHECK (status IN (0, 1)) NO INHERIT;
		-- NO INHERIT: this check constraint stays on labs.person only, not labs.users
		-- labs.users can store status = 5 without violating anything
    END IF;
END $$;

DO $$
BEGIN
    IF NOT EXISTS (
        SELECT 1 FROM pg_constraint WHERE conname = 'uq_person_id_name'
    ) THEN
        ALTER TABLE labs.person
            ADD CONSTRAINT uq_person_id_name UNIQUE (id, name);
		-- UNIQUE constraints on parent are NOT inherited by child tables
		-- (unlike CHECK constraints which ARE inherited unless NO INHERIT is specified)
    END IF;
END $$;

-- Inspect constraints on both tables
SELECT conname,
       contype,
       coninhcount,
       connoinherit
FROM pg_constraint
WHERE conrelid IN ('labs.person'::regclass, 'labs.users'::regclass);
-- this is shown in screenshot task2_8.png

/*
EXPECTED OBSERVATIONS:
- Querying parent (person) without ONLY pulls in child (users) rows automatically
- ONLY keyword restricts queries/DML to the parent table exclusively
- CHECK constraints inherited by default; NO INHERIT stops propagation
- UNIQUE, PRIMARY KEY, FOREIGN KEY, INDEX — NOT inherited (must be created
  separately on each child if needed)
- Column additions propagate to child tables automatically
- Good use case: partitioning by range/type when declarative partitioning
  isn't needed; also used in multi-tenant scenarios
*/


-----------------------------------------------------------------------------
-- TASK 3: BRIN vs B-TREE INDEXES
-----------------------------------------------------------------------------
-- BRIN (Block Range Index) stores min/max per block range instead of
-- per-row entries. It is tiny and fast to build but only useful when data
-- is physically ordered by the indexed column (e.g. time-series loaded
-- sequentially). B-Tree is the standard balanced tree index.

-- 1. Create the test table
DROP TABLE IF EXISTS labs.test_index;

CREATE TABLE labs.test_index (
    num FLOAT NOT NULL,
    load_date TIMESTAMPTZ NOT NULL
);

-- 2. Fill with ~5 years of 10-second-interval timestamps (~15.7M rows)
--    load_date is naturally ordered (sequential insert) = ideal for BRIN
INSERT INTO labs.test_index (num, load_date)
SELECT random(),
       x
FROM generate_series(
    '2017-01-01 0:00'::TIMESTAMPTZ,
    '2021-12-31 23:59:59'::TIMESTAMPTZ,
    '10 seconds'::INTERVAL
) x;
-- execution time 1m 17s

-- Check table size
SELECT pg_size_pretty(pg_relation_size('labs.test_index')) AS table_size;
-- this is shown in screenshot task3_1.png

-- 3. Baseline query (no index)
EXPLAIN ANALYZE
SELECT date_trunc('year', load_date) AS year,
       max(num) AS max_num
FROM labs.test_index
WHERE load_date BETWEEN '2021-09-01 0:00' AND '2021-10-31 11:59:59'
GROUP BY 1
ORDER BY 1;
-- Expect: Seq Scan, reads the entire table
-- this is shown in screenshot task3_2.png

-- 4a. Create B-Tree index and measure creation time
CREATE INDEX idx_test_index_btree ON labs.test_index USING btree (load_date);
-- execution time 27s

-- 4b. Re-run the query with B-Tree index active
EXPLAIN ANALYZE
SELECT date_trunc('year', load_date) AS year,
       max(num) AS max_num
FROM labs.test_index
WHERE load_date BETWEEN '2021-09-01 0:00' AND 
						'2021-10-31 11:59:59'
GROUP BY 1
ORDER BY 1;
-- Expect: Index Scan or Bitmap Index Scan, much faster for range queries
-- this is shown in screenshot task3_3.png

-- 4c. Check B-Tree index size
SELECT pg_size_pretty(pg_relation_size('idx_test_index_btree')) AS btree_index_size;
-- this is shown in screenshot task3_4.png

-- 4d. Drop B-Tree index
DROP INDEX IF EXISTS labs.idx_test_index_btree;

-- 5a. Create BRIN index and measure creation time (should be much faster)
CREATE INDEX idx_test_index_brin ON labs.test_index USING brin (load_date);
-- execution time 1.861s
-- this is shown in screenshot task3_5.png

-- 5b. Re-run the query with BRIN index active
EXPLAIN ANALYZE
SELECT date_trunc('year', load_date) AS year,
       max(num) AS max_num
FROM labs.test_index
WHERE load_date BETWEEN '2021-09-01 0:00' AND 
						'2021-10-31 11:59:59'
GROUP BY 1
ORDER BY 1;
-- Expect: Bitmap Index Scan using BRIN, fast because load_date is sequential
-- this is shown in screenshot task3_6.png

-- 5c. Check BRIN index size
SELECT pg_size_pretty(pg_relation_size('idx_test_index_brin')) AS brin_index_size;
-- this is shown in screenshot task3_7.png

-- 5d. Drop BRIN index
DROP INDEX IF EXISTS labs.idx_test_index_brin;

-- 6. Cleanup
DROP TABLE IF EXISTS labs.test_index;

/*
EXPECTED OBSERVATIONS:
- B-Tree:
    * Creation: slower (must build a full sorted tree over all rows)
    * Query: faster (direct range scan on the tree)
    * Size: large (stores an entry per indexed row value)
- BRIN:
    * Creation: much faster (just stores min/max per ~128-page block)
    * Query: fast when data is physically sequential (our case: time-series)
    * Size: tiny — often 100-1000x smaller than B-Tree
- Key insight: BRIN only works well when the physical row order correlates
  with the index column order. For random data, BRIN degrades to a full
  table scan. For our DWH fact tables loaded in date order, BRIN on
  EVENT_DT is a valid lightweight alternative to B-Tree.
*/


-----------------------------------------------------------------------------
-- TASK 4: GIN vs GiST INDEXES
-----------------------------------------------------------------------------
-- Both GIN and GiST support non-standard search operators (LIKE, full-text,
-- array containment). pg_trgm extension enables trigram-based LIKE matching
-- using either index type.

-- Prerequisite: pg_trgm extension (enables LIKE/ILIKE index support)
CREATE EXTENSION IF NOT EXISTS pg_trgm;

-- 1. Create and fill the test table
DROP TABLE IF EXISTS labs.test_index;

CREATE TABLE labs.test_index AS
SELECT id,
       md5(id::TEXT) AS t_hash
FROM generate_series(1, 10000000) AS id;
-- this is shown in screenshot task4_1.png

-- Check table size
SELECT pg_size_pretty(pg_relation_size('labs.test_index')) AS table_size;
-- this is shown in screenshot task4_2.png

-- 2. Baseline LIKE query (no index)
EXPLAIN ANALYZE
SELECT *
FROM labs.test_index
WHERE t_hash LIKE '%ceea167a5a%';
-- Expect: Seq Scan, slow, reads all 10M rows
-- this is shown in screenshot task4_3.png

-- 3a. Create GiST index using trigram operators
CREATE INDEX idx_test_index_gist
    ON labs.test_index
    USING gist (t_hash gist_trgm_ops);
-- this is shown in screenshot task4_4.png

-- 3b. Re-run the LIKE query with GiST index active
EXPLAIN ANALYZE
SELECT *
FROM labs.test_index
WHERE t_hash LIKE '%ceea167a5a%';
-- Expect: Index Scan using GiST, faster than Seq Scan
-- this is shown in screenshot task4_5.png

-- 3c. Check GiST index size
SELECT pg_size_pretty(pg_relation_size('idx_test_index_gist')) AS gist_index_size;
-- 1769 MB, this is shown in screenshot task4_6.png


-- 3d. Drop GiST index
DROP INDEX IF EXISTS labs.idx_test_index_gist;

-- 4a. Create GIN index using trigram operators
CREATE INDEX idx_test_index_gin
    ON labs.test_index
    USING gin (t_hash gin_trgm_ops);
-- this is shown in screenshot task4_7.png

-- 4b. Re-run the LIKE query with GIN index active
EXPLAIN ANALYZE
SELECT *
FROM labs.test_index
WHERE t_hash LIKE '%ceea167a5a%';
-- Expect: Bitmap Index Scan using GIN, typically faster than GiST for LIKE
-- this is shown in screenshot task4_8.png

-- 4c. Check GIN index size
SELECT pg_size_pretty(pg_relation_size('idx_test_index_gin')) AS gin_index_size;
-- 600 MB, this is shown in screenshot task4_9.png

-- 4d. Drop GIN index
DROP INDEX IF EXISTS labs.idx_test_index_gin;

-- 5. Cleanup
DROP TABLE IF EXISTS labs.test_index;

/*
OBSERVATIONS:
- Baseline (no index): Seq Scan, reads all 10M rows, slow.

- GIN is faster for LIKE queries because it stores an exact inverted index
  of trigrams with no false positives, so no table recheck is needed.
  GiST uses a lossy tree structure and must recheck matches against the
  actual rows, adding overhead.

- GiST is larger than GIN here (1769 MB vs 600 MB) because its tree
  structure requires internal node pages and padding. GIN stores each
  unique trigram once with compact posting lists.

- GiST builds faster and handles frequent updates better. GIN is the
  better choice for read-heavy workloads with rare updates, which matches
  our DWH dimension tables.
*/


-----------------------------------------------------------------------------
-- TASK 5: CSV FILE AS A FOREIGN TABLE + MATERIALIZED VIEW
-----------------------------------------------------------------------------
-- file_fdw lets PostgreSQL read a CSV on disk as if it were a regular table.
-- A materialized view caches the result set so repeated queries avoid
-- re-reading the file each time, important for large CSVs or slow storage.

-- 1. Install file_fdw extension and create the server
--    (requires superuser; run once per database)
CREATE EXTENSION IF NOT EXISTS file_fdw;

CREATE SERVER IF NOT EXISTS test_import
    FOREIGN DATA WRAPPER file_fdw;

-- 2. Create the foreign table pointing to cities_list.csv

DROP FOREIGN TABLE IF EXISTS labs.test_foreign_table;

CREATE FOREIGN TABLE labs.test_foreign_table (
    LatD INT,
    LatM INT,
    LatS INT,
    NS TEXT,
    LonD INT,
    LonM INT,
    LonS INT,
    EW TEXT,
    City TEXT,
    State TEXT
)
SERVER test_import
OPTIONS (
    filename 'C:/Program Files/PostgreSQL/18/data/cities_list.csv',
    format 'csv',
    header 'true',
    delimiter ','
);
-- this is shown in screenshot task5_1.png

-- 3. Select all rows and count from the foreign table
SELECT *
FROM labs.test_foreign_table;
-- this is shown in screenshot task5_2.png

SELECT count(*) AS total_cities
FROM labs.test_foreign_table;
-- Expected: 128 rows (the full cities_list.csv)
-- this is shown in screenshot task5_3.png

-- 4. Create a materialized view on top of the foreign table
--    Materialized views store the result set physically, unlike regular views.
--    Queries against the mview hit local storage, not the CSV file each time.

DROP MATERIALIZED VIEW IF EXISTS labs.mv_cities;

CREATE MATERIALIZED VIEW labs.mv_cities AS
    SELECT *
    FROM labs.test_foreign_table;

-- Select from the materialized view
SELECT *
FROM labs.mv_cities;
-- this is shown in screenshot task5_4.png

SELECT count(*) AS mview_count
FROM labs.mv_cities;
-- Should match the foreign table count
-- this is shown in screenshot task5_5.png

-- 5. Simulate deletion from file:
--    Open cities_list.csv in a text editor and delete a few rows, then save.
--    Now query the foreign table again,count drops immediately (reads live file).
SELECT count(*) AS foreign_table_count_after_deletion
FROM labs.test_foreign_table;
-- this is shown in screenshot task5_6.png

-- But the materialized view still shows the OLD count (it is stale/cached):
SELECT count(*) AS mview_count_before_refresh
FROM labs.mv_cities;
-- this is shown in screenshot task5_7.png

-- 6. Refresh the materialized view to sync with the updated CSV
REFRESH MATERIALIZED VIEW labs.mv_cities;

SELECT count(*) AS mview_count_after_refresh
FROM labs.mv_cities;
-- Now matches the foreign table count (deleted rows no longer appear)
-- this is shown in screenshot task5_8.png

/*
EXPECTED OBSERVATIONS:
- Foreign table (file_fdw): reads the CSV file on every query — always
  shows current file state. No data is stored in PostgreSQL.
- Materialized view: stores a physical snapshot of the data at refresh time.
  Queries are fast (local table scan). But data goes stale until you REFRESH.
- REFRESH MATERIALIZED VIEW is a blocking operation (table locked during
  refresh). Use REFRESH MATERIALIZED VIEW CONCURRENTLY to allow reads during
  refresh (requires a UNIQUE index on the view first).
- Real-world DWH parallel: our EXT_ foreign tables (file_fdw on CSVs) are
  like the foreign table here. Our SRC_ tables are like the materialized view,
  a snapshot taken at load time, refreshed on each ETL run.
*/


-- CLEANUP
-----------------------------------------------------------------------------
-- DROP TABLE IF EXISTS labs.test_simple;
-- DROP TABLE IF EXISTS labs.test_unlogged;
-- DROP TABLE IF EXISTS labs.users CASCADE;
-- DROP TABLE IF EXISTS labs.person CASCADE;
-- DROP MATERIALIZED VIEW IF EXISTS labs.mv_cities;
-- DROP FOREIGN TABLE IF EXISTS labs.test_foreign_table;