-- DIM_TIME_DAY: Date Dimension
-- Populated once for the full 2024-2025 range
-- Schema: BL_DM
-------------------------------------------------------------

DROP TABLE IF EXISTS BL_DM.DIM_TIME_DAY;

CREATE TABLE BL_DM.DIM_TIME_DAY (
    DATE_ID INTEGER NOT NULL,
    DATE_DT DATE NOT NULL,
    DAY_OF_WEEK_NO INTEGER NOT NULL,
    DAY_OF_WEEK_DESC VARCHAR(25) NOT NULL,
    WEEKEND_FLAG INTEGER NOT NULL,
    ISO_WEEK_NO INTEGER NOT NULL,
    DAY_OF_MONTH_NO INTEGER NOT NULL,
    MONTH_VALUE VARCHAR(2) NOT NULL,
    MONTH_DESC VARCHAR(25) NOT NULL,
    QUARTER_VALUE VARCHAR(1) NOT NULL,
    QUARTER_DESC VARCHAR(2) NOT NULL,
    YEAR_VALUE VARCHAR(4) NOT NULL,
    INSERT_DT DATE NOT NULL,
    UPDATE_DT DATE NOT NULL,
    CONSTRAINT PK_DIM_TIME_DAY PRIMARY KEY (DATE_ID)
);


-- Populate DIM_TIME_DAY for 2024-01-01 to 2025-12-31
-------------------------------------------------------------

INSERT INTO BL_DM.DIM_TIME_DAY (
    DATE_ID,
    DATE_DT,
    DAY_OF_WEEK_NO,
    DAY_OF_WEEK_DESC,
    WEEKEND_FLAG,
    ISO_WEEK_NO,
    DAY_OF_MONTH_NO,
    MONTH_VALUE,
    MONTH_DESC,
    QUARTER_VALUE,
    QUARTER_DESC,
    YEAR_VALUE,
    INSERT_DT,
    UPDATE_DT
)
SELECT
    TO_CHAR(d.dt, 'YYYYMMDD')::INTEGER AS DATE_ID,
    d.dt AS DATE_DT,
    EXTRACT(ISODOW FROM d.dt)::INTEGER AS DAY_OF_WEEK_NO,
    TO_CHAR(d.dt, 'Day') AS DAY_OF_WEEK_DESC,
    CASE WHEN EXTRACT(ISODOW FROM d.dt) IN (6, 7)
         THEN 1 ELSE 0 END  AS WEEKEND_FLAG,
    EXTRACT(WEEK FROM d.dt)::INTEGER AS ISO_WEEK_NO,
    EXTRACT(DAY FROM d.dt)::INTEGER AS DAY_OF_MONTH_NO,
    TO_CHAR(d.dt, 'MM') AS MONTH_VALUE,
    TO_CHAR(d.dt, 'Month') AS MONTH_DESC,
    TO_CHAR(EXTRACT(QUARTER FROM d.dt)::INTEGER, '9') AS QUARTER_VALUE,
    'Q' || EXTRACT(QUARTER FROM d.dt)::INTEGER AS QUARTER_DESC,
    TO_CHAR(d.dt, 'YYYY') AS YEAR_VALUE,
    CURRENT_DATE AS INSERT_DT,
    CURRENT_DATE AS UPDATE_DT
FROM (
    SELECT GENERATE_SERIES(
        '2024-01-01'::DATE,
        '2025-12-31'::DATE,
        '1 day'::INTERVAL
    )::DATE AS dt
) d;